name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
        
      - name: Build extension
        run: npm run build
        
      - name: Run tests
        run: npm run test:e2e
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 Chrome Extension Release ${{ github.ref_name }}
            
            ### 📦 Extension Package
            Download the extension ZIP from the artifacts below.
            
            ### 🧪 Test Results
            All E2E tests passed successfully.
            
            ### 📋 Installation Instructions
            1. Download the `extension.zip` file
            2. Extract the ZIP file
            3. Open Chrome and go to `chrome://extensions/`
            4. Enable "Developer mode"
            5. Click "Load unpacked" and select the extracted folder
            
            ### 🔧 Development
            - Source code: [GitHub Repository](https://github.com/${{ github.repository }})
            - Issues: [Report Issues](https://github.com/${{ github.repository }}/issues)
          draft: false
          prerelease: false
          
      - name: Upload Extension Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip
